# config/base_config.yaml
# Default configurations for all entity types.
# Override specific fields in config/override_config.yaml

defaults:
  api_version: "v61.0"
  dataspace_name: "default"

# ─── Datastreams ──────────────────────────────────────────────────────────────
datastreams:
  base:
    dataSpaceName: "default"
    type: "CRM"
    status: "Running"

# ─── DMOs ─────────────────────────────────────────────────────────────────────
dmos:
  base:
    dataSpaceName: "default"
    category: "Profile"

# ─── Segments ─────────────────────────────────────────────────────────────────
segments:
  base:
    segmentType: "UI"
    developerName: "default_segment_name"
    description: "Default segment"
    segmentOnApiName: "ssot__Individual__dlm"
    segmentCreationFlow: "datakit"

# ─── Targets ──────────────────────────────────────────────────────────────────
targets:
  base:
    platformType: "AmazonS3"
    isCappingEnabled: false
    description: "Default target description"
    connector:
      bucketName: "your-bucket-name"
      folderName: "default/folder/"
    dataSpaceName: "default"

# ─── Activations ──────────────────────────────────────────────────────────────
activations:
  base:
    refreshType: "FULL_REFRESH"
    dataSpaceName: default
    activationTargetName: "test_target_1"
    name: "Activation_1"
    segmentApiName: "test"
    activationTargetSubjectConfig:
      developerName: ssot__Individual__dlm
    attributesConfig:
      attributes:
        - dataSourceType: "Text"
          entityName: "ssot__Individual__dlm"
          label: "Individual Id"
          name: "ssot__Id__c"
          queryPathConfig:
            configs: []
          referenceAttributeName: "Id"
          source: "DIRECT"
          type: "MODEL"
    shouldExcludeDeletes: false
    shouldExcludeUpdates: false
    staticDataConfig:
      staticData:
        - name: "Name 1"
          value: "Value 1"

# ─── Connectors ───────────────────────────────────────────────────────────────
connectors:
  base:
    name: SFTP_Connector
    connectorType: SFTP
    label: Secure File Transfer (SFTP)
    method: Egress
